<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../../static/style/styleForMenu.css">
    <link rel="stylesheet" href="../../static/style/errors/styleForError.css">

    <title>500</title>

</head>
<body>

<div class="error-main">
    <h1>Oops!</h1>
    <div class="error-heading">500</div>
    <p>Sorry, it's me, not you.</p>
</div>
<a href="/signIn" class="cats">Выйти</a>
</body>
</html>