spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mimicats
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false